server:
  port: 8081

spring:
  application:
    name: offre-service
  datasource:
    url: jdbc:mysql://mysql:3306/offre_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: offre_user
    password: offre_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8180/realms/microservices-realm
          jwk-set-uri: http://keycloak:8180/realms/microservices-realm/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Keycloak Security
keycloak:
  realm: microservices-realm
  auth-server-url: http://keycloak:8180
  resource: offre-service-client
  credentials:
    secret: S3cr3t-0ffr3-S3rv1c3-K3y-2024
  use-resource-role-mappings: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
