{
 "title": "Job Portal - Microservices Overview",
 "tags": [
  "job-portal",
  "microservices"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Services UP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up == 1)", "legendFormat": "Services UP" }
   ]
  },
  {
   "title": "Services DOWN",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up == 0)", "legendFormat": "Services DOWN" }
   ]
  },
  {
   "title": "Etat des services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Requetes HTTP Spring Boot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Requetes HTTP Candidature Node.js",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(candidature_service_http_requests_total[1m])",
     "legendFormat": "candidature-service-nodejs"
    }
   ]
  }
 ]
}