apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: job-portal
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ["prometheus:9090"]

      - job_name: api-gateway
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ["api-gateway:8080"]

      - job_name: offre-service
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ["offre-service:8081"]

      - job_name: candidature-service-nodejs
        metrics_path: /metrics
        static_configs:
          - targets: ["candidature-service:8082"]

      - job_name: eureka-server
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ["eureka-server:8761"]

      - job_name: config-server
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ["config-server:8888"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: job-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.53.0
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: job-portal
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: job-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.4.6
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: job-portal
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
