spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      fail-fast: false
      retry:
        max-attempts: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
